export const SELECTED_DRIVER = "SELECTED_DRIVER";
export const SELECTED_ASSIGNMENT = "SELECTED_ASSIGNMENT";
export const TRIGER_CHOOSING_DRIVER = "TRIGER_CHOOSING_DRIVER";
export const TRIGER_CHOOSING_ASSIGNMENT = "TRIGER_CHOOSING_ASSIGNMENT";
